### ISSUE TITLE
Translate the location 

### ISSUE THREAD

**Issue by LinaKurbeh** [jannickbath/projektarbeit-new#4]

**Comment by LinaKurbeh** [comment]
`const request = require('request');

function options(text) {
    return {
        method: 'POST',
        url: 'https://google-translator9.p.rapidapi.com/v2/detect',
        headers: {
            'content-type': 'application/json',
            'X-RapidAPI-Key': '3a72ab552bmsh720d0c146db33b3p1f7a16jsn44a6091f97cf',
            'X-RapidAPI-Host': 'google-translator9.p.rapidapi.com'
        },
        body: {q: text},
        json: true
    };
}

function getLanguage(text){
    let optionsLanguage = options(text)
    let resourceLanguage;
    request(optionsLanguage, function (error, response, body) {
        if (error) throw new Error(error);

        console.log((body.data.detections[0][0].language));
        resourceLanguage = body.data.detections[0][0].language;
    });
    return resourceLanguage
}

function optionsTranslate(text) {
    return {
        method: 'POST',
        url: 'https://google-translator9.p.rapidapi.com/v2',
        headers: {
            'content-type': 'application/json',
            'X-RapidAPI-Key': '3a72ab552bmsh720d0c146db33b3p1f7a16jsn44a6091f97cf',
            'X-RapidAPI-Host': 'google-translator9.p.rapidapi.com'
        },
        body: {
            q: text,
            source: getLanguage(text),
            target: 'en',
            format: 'text'
        },
        json: true
    };
}
function translate(text){
    let options = optionsTranslate(text);
    let translatedText;
    request(options, function (error, response, body) {
        if (error) throw new Error(error);

        translatedText = body.data.translations[0].translatedText;
    });
    return translatedText;
}
`

**Comment by LinaKurbeh** [comment]
@jannickbath hi.. ich habe einen Code für Übersetzen geschrieben! aber konnte nicht richtig im Code implementieren!!
Ich denke wir brauchen die Seite jede 10min. wieder aufzurufen.

**Comment by jannickbath** [comment]
Diese Funktionalität ist unnötig. Das ursprüngliche Problem lag darin, dass die API die englischen Namen der Orte zurückgibt. Dabei gab es einen Fehler, wenn die api responses von firestore abgefragt werden. 
Das Problem wurde bereits im Commit 0993208bfe7358e0174afcf9451237af40ba0017 behoben.
